- 전처리

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'who', 'deck']]
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked    who deck
0         0       3    male  22.0      1      0   7.2500        S    man  NaN
1         1       1  female  38.0      1      0  71.2833        C  woman    C
2         1       3  female  26.0      0      0   7.9250        S  woman  NaN
3         1       1  female  35.0      1      0  53.1000        S  woman    C
4         0       3    male  35.0      0      0   8.0500        S    man  NaN

In [5]:
df.isna().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
who           0
deck        688
dtype: int64

In [7]:
df.who.value_counts()

man      537
woman    271
child     83
Name: who, dtype: int64

In [12]:
df['age'] = df.groupby('who', group_keys=True)['age'].apply(lambda x: x.fillna(x.mean()))
df.tail()

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\human\anaconda3\Lib\site-packages\pandas\core\frame.py", line 12020, in _reindex_for_setitem
    reindexed_value = value.reindex(index)._values
                      ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\human\anaconda3\Lib\site-packages\pandas\core\series.py", line 5094, in reindex
    return super().reindex(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\human\anaconda3\Lib\site-packages\pandas\core\generic.py", line 5289, in reindex
    return self._reindex_axes(
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\human\anaconda3\Lib\site-packages\pandas\core\generic.py", line 5304, in _reindex_axes
    new_index, indexer = ax.reindex(
                         ^^^^^^^^^^^
  File "c:\Users\human\anaconda3\Lib\site-packages\pandas\core\indexes\base.py", line 4434, in reindex
    target = self._wrap_reindex_result(target, indexer, preserve_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Fil

In [14]:
df.isna().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      2
who           0
deck        688
dtype: int64

In [15]:
df.embarked.value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [16]:
df.embarked.fillna('S', inplace=True)
df.isna().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
who           0
deck        688
dtype: int64

In [18]:
df.drop(columns=['who', 'deck'], inplace=True)
df.isna().sum().sum()

0

In [19]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [20]:
from sklearn.preprocessing import LabelEncoder
df.sex = LabelEncoder().fit_transform(df.sex)
df.embarked = LabelEncoder().fit_transform(df.embarked)
df.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [22]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(df.iloc[:, 1:].values)
y = df.iloc[:, 0]
X_std[0], y[0]

(array([ 0.82737724,  0.73769513, -0.63718871,  0.43279337, -0.47367361,
        -0.50244517,  0.58595414]),
 0)

- SVM

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_std, y, stratify=y, test_size=0.2, random_state=2023
)

In [27]:
from sklearn.svm import SVC
svc = SVC(random_state=2023, probability=True)
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.7877094972067039

In [35]:
svc.predict_proba(X_test[:5])

array([[0.85361223, 0.14638777],
       [0.51007098, 0.48992902],
       [0.84699829, 0.15300171],
       [0.84686037, 0.15313963],
       [0.84686564, 0.15313436]])

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.7877094972067039

In [34]:
knn.predict_proba(X_test[:5])

array([[0.8, 0.2],
       [0.4, 0.6],
       [1. , 0. ],
       [0.8, 0.2],
       [1. , 0. ]])

In [36]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=2023)
lrc.fit(X_train, y_train)
lrc.score(X_test, y_test)

0.7486033519553073

In [38]:
lrc.predict_proba(X_test[:5])

array([[0.78638828, 0.21361172],
       [0.13439913, 0.86560087],
       [0.78109722, 0.21890278],
       [0.85592416, 0.14407584],
       [0.92178881, 0.07821119]])

- Ensemble / Voting / Hard

In [42]:
from sklearn.ensemble import VotingClassifier
voc = VotingClassifier(
    estimators=[('SVC', svc), ('KNN', knn), ('LRC', lrc)],
    voting='hard'
)
voc.fit(X_train, y_train)
voc.score(X_test, y_test)

0.7821229050279329

In [43]:
voc.predict_proba(X_test[:5])        # hard voting에는 적용 안됨.

AttributeError: predict_proba is not available when voting='hard'

- Ensemble / Voting / Soft

In [44]:
voc2 = VotingClassifier(
    estimators=[('SVC', svc), ('KNN', knn), ('LRC', lrc)],
    voting='soft'
)
voc2.fit(X_train, y_train)
voc2.score(X_test, y_test)

0.8044692737430168

In [52]:
voc2.get_params()

{'estimators': [('SVC', SVC(probability=True, random_state=2023)),
  ('KNN', KNeighborsClassifier()),
  ('LRC', LogisticRegression(random_state=2023))],
 'flatten_transform': True,
 'n_jobs': None,
 'verbose': False,
 'voting': 'soft',
 'weights': None,
 'SVC': SVC(probability=True, random_state=2023),
 'KNN': KNeighborsClassifier(),
 'LRC': LogisticRegression(random_state=2023),
 'SVC__C': 1.0,
 'SVC__break_ties': False,
 'SVC__cache_size': 200,
 'SVC__class_weight': None,
 'SVC__coef0': 0.0,
 'SVC__decision_function_shape': 'ovr',
 'SVC__degree': 3,
 'SVC__gamma': 'scale',
 'SVC__kernel': 'rbf',
 'SVC__max_iter': -1,
 'SVC__probability': True,
 'SVC__random_state': 2023,
 'SVC__shrinking': True,
 'SVC__tol': 0.001,
 'SVC__verbose': False,
 'KNN__algorithm': 'auto',
 'KNN__leaf_size': 30,
 'KNN__metric': 'minkowski',
 'KNN__metric_params': None,
 'KNN__n_jobs': None,
 'KNN__n_neighbors': 5,
 'KNN__p': 2,
 'KNN__weights': 'uniform',
 'LRC__C': 1.0,
 'LRC__class_weight': None,
 'LRC__du

In [47]:
voc2.predict_proba(X_test[:5])

array([[0.8133335 , 0.1866665 ],
       [0.3481567 , 0.6518433 ],
       [0.87603184, 0.12396816],
       [0.83426151, 0.16573849],
       [0.92288482, 0.07711518]])

- Ensemble / Bagging / Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=2023)
rfc.fit(X_train, y_train)
rfc.score(X_test, y_test)

0.770949720670391

In [51]:
rfc.predict_proba(X_test[:5])

array([[0.51566667, 0.48433333],
       [0.31      , 0.69      ],
       [1.        , 0.        ],
       [0.94      , 0.06      ],
       [0.96      , 0.04      ]])

- GridSearchCV / Ensemble / Voting / Soft

In [53]:
from sklearn.model_selection import GridSearchCV
params = {
    'SVC__C': [0.1, 1, 5, 10, 100],
    'LRC__C': [0.1, 1, 5, 10, 100]
}
grid_voc = GridSearchCV(voc2, params, scoring='accuracy', cv=5)
grid_voc.fit(X_train, y_train)
grid_voc.score(X_test, y_test)

0.7988826815642458

In [54]:
grid_voc.best_params_

{'LRC__C': 0.1, 'SVC__C': 0.1}

In [55]:
params = {
    'SVC__C' : [0.05, 0.1, 0.3, 1],
    'LRC__C' : [0.05, 0.1, 0.3, 1]
}
grid_voc = GridSearchCV(voc2, params, scoring='accuracy', cv=5)
grid_voc.fit(X_train, y_train)
grid_voc.best_params_

{'LRC__C': 0.1, 'SVC__C': 0.3}

In [56]:
params = {
    'SVC__C' : [0.2, 0.3, 0.4],
    'LRC__C' : [0.05, 0.1, 0.2]
}
grid_voc = GridSearchCV(voc2, params, scoring='accuracy', cv=5)
grid_voc.fit(X_train, y_train)
grid_voc.best_params_

{'LRC__C': 0.05, 'SVC__C': 0.4}

In [58]:
best_grid_voc = grid_voc.best_estimator_
pred = best_grid_voc.predict(X_test)
df1 = pd.DataFrame({'y 실제값': y_test, 'y 예측값': pred})
df1.head()

y 실제값  y 예측값
800      0      0
341      1      1
413      0      0
575      0      0
202      0      0

In [59]:
lrc.C, svc.C 

(1.0, 1.0)