In [1]:
import numpy as np

# 두 변수 X와 Y의 데이터 포인트 예시
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])

# 평균 계산
mean_X = np.mean(X)
mean_Y = np.mean(Y)

# 공분산 계산
n = len(X)
covariance = np.sum((X - mean_X) * (Y - mean_Y)) / (n - 1)

print("X와 Y의 공분산:", covariance)

X와 Y의 공분산: -2.5


In [2]:
import numpy as np

# 세 변수 X, Y, Z의 데이터 포인트 예시
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])
Z = np.array([2, 3, 4, 5, 6])

# 평균 계산
mean_X = np.mean(X)
mean_Y = np.mean(Y)
mean_Z = np.mean(Z)

# 공분산 계산
n = len(X)
covariance_XY = np.sum((X - mean_X) * (Y - mean_Y)) / (n - 1)
covariance_XZ = np.sum((X - mean_X) * (Z - mean_Z)) / (n - 1)
covariance_YZ = np.sum((Y - mean_Y) * (Z - mean_Z)) / (n - 1)

print("X와 Y의 공분산:", covariance_XY)
print("X와 Z의 공분산:", covariance_XZ)
print("Y와 Z의 공분산:", covariance_YZ)

X와 Y의 공분산: -2.5
X와 Z의 공분산: 2.5
Y와 Z의 공분산: -2.5


In [2]:
import numpy as np

# 두 변수 X와 Y의 데이터 포인트 예시
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])

# X와 Y를 하나의 데이터 행렬로 정의
data = np.vstack((X, Y))

# 평균 계산
mean_data = np.mean(data, axis=1)

# 공분산 행렬 계산
cov_matrix = np.cov(data)

# 공분산 행렬의 고유값과 고유벡터 계산
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("공분산 행렬:")
print(cov_matrix)
print("\n고유값 (Eigenvalues):")
print(eigenvalues)
print("\n고유벡터 (Eigenvectors):")
print(eigenvectors)

공분산 행렬:
[[ 2.5 -2.5]
 [-2.5  2.5]]

고유값 (Eigenvalues):
[5.00000000e+00 5.55111512e-16]

고유벡터 (Eigenvectors):
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [3]:
import numpy as np

# 두 변수 X와 Y의 데이터 포인트 예시
X = np.array([1, 2, 3, 4, 5])
Y = np.array([5, 4, 3, 2, 1])

# 평균 계산
mean_X = np.mean(X)
mean_Y = np.mean(Y)

# 각 변수의 편차 계산
deviation_X = X - mean_X
deviation_Y = Y - mean_Y

# 공분산 행렬 계산
n = len(X)
cov_matrix = np.zeros((2, 2))

# (1,1) 요소는 X의 분산
cov_matrix[0, 0] = np.sum(deviation_X**2) / (n - 1)

# (2,2) 요소는 Y의 분산
cov_matrix[1, 1] = np.sum(deviation_Y**2) / (n - 1)

# (1,2) 및 (2,1) 요소는 X와 Y의 공분산
cov_matrix[0, 1] = cov_matrix[1, 0] = np.sum(deviation_X * deviation_Y) / (n - 1)

print("공분산 행렬:")
print(cov_matrix)

공분산 행렬:
[[ 2.5 -2.5]
 [-2.5  2.5]]
